project:
  type: website
  output-dir: docs

website:
  title: "Francis Banville"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
      - publications.qmd
      - cv.qmd
      - miscellaneous.qmd

format:
  html:
    theme: 
      dark: Solar
      light: Flatly 
    css: styles.css
    toc: true

editor: visual

