project:
  type: website
  output-dir: docs

website:
  title: "Francis Banville"
  favicon: pictures/icons/otter.png
  navbar:
    title: false
    logo: pictures/logo/logo-transparent-cropped.png
    logo-alt: "The web of Francis"
    background: primary
    left:
      - href: index.qmd
        text: home
      - projects.qmd
      - publications.qmd
      - miscellaneous.qmd
    right: 
      - href: CV/CV_EN.pdf
        text: CV
      - icon: github
        href: https://github.com/FrancisBanville
      - icon: twitter
        href: https://twitter.com/francisbanv
  page-footer:     
      background: light 
      left: 
        - "Copyright 2023, Francis Banville"
      right: 
        - icon: github
          href: https://github.com/FrancisBanville
        - icon: twitter
          href: https://twitter.com/francisbanv

format:
  html:
    theme: 
      dark: [Solar, mystyles.scss]
      light: Flatly 
    mainfont: Gelasio
    css: styles.css
    toc: true

editor: visual

