---
editor: source
cap-location: margin
---

# Teaching experience

## Courses

##### BIO2041 Biostatistique 1
Course instructor: Dr. Alexandre Collin\
*Université de Montréal*\
[{{< fa road >}} course syllabus (fall 2022)](https://bio.umontreal.ca/public/FAS/biologie/Documents/1-Programmes-cours/Cours_et_horaires/AUTOMNE_2022/BIO2041.pdf), [{{< fa building-columns >}} admission](https://admission.umontreal.ca/cours-et-horaires/cours/bio-2041/)

**Head teaching assistant:** {{< fa ghost >}} fall 2022\
**Teaching assistant:** <i class="fa-solid fa-sun" style="color: #dec317;"></i>
summers 2022-23\
**Tutor:** <i class="fa-solid fa-sun" style="color: #dec317;"></i> summers 2020-23\

<details style="font-size:17px">
<summary>course description</summary>
Biological statistics. Parameters of a distribution. Probability distributions. Confidence intervals. Decision theory. Comparison of two samples. Correlation. Analysis of variance. Chi-square tests. Regression
</details>

<br>

##### BIO2042 Biostatistique 2
Course instructor: Dr. Alexandre Collin\
*Université de Montréal*\
[{{< fa road >}} course syllabus (winter 2023)](https://bio.umontreal.ca/public/FAS/biologie/Documents/1-Programmes-cours/Cours_et_horaires/HIVER_2023/BIO2042.pdf), [{{< fa building-columns >}} admission](https://admission.umontreal.ca/cours-et-horaires/cours/bio-2042/)

**Teaching assistant:** <i class="fa-solid fa-snowflake" style="color: #194ca4;"></i>
winter 2023\
**Tutor:** <i class="fa-solid fa-snowflake" style="color: #194ca4;"></i> winter 2023\

<details style="font-size:17px">
<summary>course description</summary>
Advanced analysis of biological variation. Multiple regression, model II regression, multi-criteria classification and hierarchical ANOVA, analysis of covariance. Introduction to multivariate analysis.
</details>

<br>

##### BIO2811 Dynamique des populations
Course instructor: Pr. Daniel Boisclair\
*Université de Montréal*\
[{{< fa road >}} course syllabus (winter 2022)](https://bio.umontreal.ca/public/FAS/biologie/Documents/1-Programmes-cours/Cours_et_horaires/HIVER_2022/cycles_sup%C3%A9rieurs/BIO2811_6034.pdf), [{{< fa building-columns >}} admission](https://admission.umontreal.ca/cours-et-horaires/cours/bio-2811/)

**Grader:** <i class="fa-solid fa-snowflake" style="color: #194ca4;"></i>
winters 2021-22 

<details style="font-size:17px">
<summary>course description</summary>
Processes responsible for temporal variations in the abundance of animal and plant populations. Description and use of mathematical models to quantify and predict variations in population abundance.
</details>

<br>

##### BIO1001 Méthodes de recherche en biologie (TP)
Course instructor: Pr. Éric Harvey\
*Université de Montréal*\
[{{< fa road >}} course syllabus (fall 2021)](https://bio.umontreal.ca/public/FAS/biologie/Documents/1-Programmes-cours/Cours_et_horaires/AUTOMNE_2021/BIO1001__Automne2021_PC_HarveyE.pdf), [{{< fa building-columns >}} admission](https://admission.umontreal.ca/cours-et-horaires/cours/bio-1001/)

**Grader:** {{< fa ghost >}} fall 2021

<details style="font-size:17px">
<summary>course description</summary>
Presentation of the basic principles of research work, including laboratory practices, the use of libraries and bibliographic databases, and the acquisition, processing and presentation of scientific data.
</details>

<br>

##### BIO6065 École d'été en synthèse écologique de données
Course instructor: Pr. Timothée Poisot\
*Université de Montréal*\
[{{< fa road >}} course syllabus (summer 2021)](https://bio.umontreal.ca/public/FAS/biologie/Documents/1-Programmes-cours/Cours_et_horaires/ETE_2021/cycles_sup%C3%A9rieurs/BIO6065_E2021_PC_PoisotT.pdf), [{{< fa building-columns >}} admission](https://admission.umontreal.ca/cours-et-horaires/cours/bio-6065/)

**Teaching assistant:** <i class="fa-solid fa-sun" style="color: #dec317;"></i> summer 2021

<details style="font-size:17px">
<summary>course description</summary>
This one-week advanced training course will present, through projects, the most advanced data mining methods for working with ecological data.
</details>

<br>

##### BIO3043 Théorie des réseaux
Course instructor: Pr. Timothée Poisot\
*Université de Montréal*\
[{{< fa road >}} course syllabus (fall 2020)](https://bio.umontreal.ca/public/FAS/biologie/Documents/1-Programmes-cours/Cours_et_horaires/AUTOMNE_2020/cycles_sup%C3%A9rieurs/BIO3043-6037_PCA20_TPoisot.pdf), [{{< fa building-columns >}} admission](https://admission.umontreal.ca/cours-et-horaires/cours/bio-3043/)

**Teaching assistant:** {{< fa ghost >}} fall 2020

<details style="font-size:17px">
<summary>course description</summary>
Description of ecological communities from the perspective of network theory, structure of interactions between species, prediction of emergent properties of ecosystems, spatial and evolutionary dynamics of community structure. 
</details>

<br>

## Workshops

##### Twitch workshops
Poisot lab\
[<i class="fa-brands fa-youtube"></i> Twitch channel](https://www.twitch.tv/poisotlab)\

**Co-presenter:**\
Species distribution models in Julia (2022, June 20-21, *virtual* )\

<br>

##### Data.Trek
Institute for Data Valorization (IVADO)\
[{{< fa laptop >}} Data.Trek challenge](https://ivado.ca/en/events/the-100-days-of-data-trek-challenge-2/)\

**Lead presenter:**\
Machine learning and ecological network analysis in Julia (2020, March 5, *Montreal* )\
[{{< fa code >}} intro to `Mangal.jl`](https://nextjournal.com/francisbanville/mangaljl---introduction?change-id=Cn7Gz8vBKYoU35uCVocWy5), 
[{{< fa code >}} intro to `EcologicalNetworks.jl`](https://nextjournal.com/francisbanville/introduction-%C3%A0-ecologicalnetworks?change-id=Cms9YrJvJjKLbuMEQaYiXn),
[{{< fa code >}} intro to `Flux.jl`](https://nextjournal.com/francisbanville/training-neural-networks-using-fluxjl-master?change-id=DSPowrWu4kn8RY1souLZax)\

**Co-presenter:**\
Introduction to R (2020, March 5, *Montreal* )\

**Programming mentor:** <i class="fa-solid fa-snowflake" style="color: #194ca4;"></i> winters 2020 and 22\

<br>

##### Software carpentry
Computational Biodiversity Science & Services program (BIOS²)\
[{{< fa laptop >}} software carpentry](https://software-carpentry.org/)

**Co-presenter:**\
Programming in R (2021, November 23-26, *Rimouski* )\

**Presentation assistant:**\
Introduction to Git (2021, November 22, *Rimouski* )\

<br>

##### QCBS R workshops
Quebec Centre for Biodiversity Science (QCBS)\
[{{< fa frog >}} R workshops](https://r.qcbs.ca/)

**Lead presenter:**\
[{{< fa code >}} workshop 5](https://r.qcbs.ca/workshops/r-workshop-05/): Programming in R (2019, November 29, *Montreal* )\

**Presentation assistant:**\
[{{< fa code >}} workshop 6](https://r.qcbs.ca/workshops/r-workshop-06/)
: Generalized linear models in R (2021, March 11, *virtual* )\
[{{< fa code >}} workshop 8](https://r.qcbs.ca/workshops/r-workshop-08/)
: Generalized additive models in R (2021, April 1, *virtual* )\

# Completed graduate courses

### Credited courses 

##### BIO6004 Communication scientifique
Fall 2018, *Université de Montréal*\
[{{< fa road >}} course syllabus](https://bio.umontreal.ca/public/FAS/biologie/Documents/1-Programmes-cours/Cours_et_horaires/AUTOMNE_2018/BIO4000_A18_c1_c2.pdf), [{{< fa building-columns >}} admission](https://admission.umontreal.ca/cours-et-horaires/cours/bio-6004/)

##### BIO6032 Biologie computationnelle et modélisation
Winter 2019, *Université de Montréal*\
[{{< fa road >}} course syllabus](https://bio.umontreal.ca/public/FAS/biologie/Documents/1-Programmes-cours/Cours_et_horaires/HIVER_2020/cycles_sup%C3%A9rieurs/BIO6032_PC_H20-TPoisot.pdf), [{{< fa building-columns >}} admission](https://admission.umontreal.ca/cours-et-horaires/cours/bio-6032/)

##### BIO6033 Méthodes quantitatives en biologie
Winter 2019, *Université de Montréal*\
[{{< fa building-columns >}} admission](https://admission.umontreal.ca/cours-et-horaires/cours/bio-6033/)

##### BIO6037 Analyse des réseaux écologiques
Fall 2019, *Université de Montréal*\
[{{< fa road >}} course syllabus](https://bio.umontreal.ca/public/FAS/biologie/Documents/1-Programmes-cours/Cours_et_horaires/AUTOMNE_2019/BIO3043_PC_A19-TPoisot.pdf), [{{< fa building-columns >}} admission](https://admission.umontreal.ca/cours-et-horaires/cours/bio-6037/)

##### BIO6063 Travail dirigé 1
Supervisors: Pr. Jean-François Lapierre and Pr. Roxanne Maranger\
Summer 2019, *Université de Montréal*\
[{{< fa building-columns >}} admission](https://admission.umontreal.ca/cours-et-horaires/cours/bio-6063/)

##### BIO6065 École d'été en synthèse écologique de données
Summer 2019, *Université de Montréal*\
[{{< fa building-columns >}} admission](https://admission.umontreal.ca/cours-et-horaires/cours/bio-6065/)

##### BIO6077 Analyse quantitative des données
Fall 2018, *Université de Montréal*\
[{{< fa road >}} course syllabus](https://bio.umontreal.ca/public/FAS/biologie/Documents/1-Programmes-cours/Cours_et_horaires/HIVER_2019/Cycles_superieurs/BIO6077_H2019_PC_LegendreP.pdf), [{{< fa building-columns >}} admission](https://admission.umontreal.ca/cours-et-horaires/cours/bio-6077/)

##### BIO6115 Progrès en phylogénie systématique
Winter 2019, *Université de Montréal*\
[{{< fa road >}} course syllabus](https://bio.umontreal.ca/public/FAS/biologie/Documents/1-Programmes-cours/Cours_et_horaires/HIVER_2019/BIO3115-6115_PC_H19_ABrunneau.pdf), [{{< fa building-columns >}} admission](https://admission.umontreal.ca/cours-et-horaires/cours/bio-6115/)

##### BIO6260 Génomique microbienne
Fall 2018, *Université de Montréal*\
[{{< fa road >}} course syllabus](https://bio.umontreal.ca/public/FAS/biologie/Documents/1-Programmes-cours/Cours_et_horaires/AUTOMNE_2018/Cycles_superieurs/BIO3260-6260_A18.pdf
), [{{< fa building-columns >}} admission](https://admission.umontreal.ca/cours-et-horaires/cours/bio-6260/)

##### BIO860M Séminaire thématique en écologie
Winter 2021, *UQAM*\
[{{< fa building-columns >}} admission](https://etudier.uqam.ca/cours?sigle=BIO860M)

##### GEO6321 Travaux pratiques en géomatique 
Fall 2018, *Université de Montréal*\
[{{< fa building-columns >}} admission](https://studium.umontreal.ca/enrol/index.php?id=85500)

##### MSO6028 Introduction aux théories de la mesure
Winter 2019, *Université de Montréal*\
[{{< fa road >}} course syllabus](https://espum.umontreal.ca/fileadmin/espum/documents/ESPUM/SYLLABUS/30_MSO6028_H17.pdf), [{{< fa building-columns >}} admission](https://admission.umontreal.ca/cours-et-horaires/cours/mso-6028/)

### Extracurricular courses

##### ECL807 École d’été en modélisation de la biodiversité 2021
Summer 2021, *Université de Sherbrooke*\
[{{< fa building-columns >}} admission](https://www.usherbrooke.ca/admission/fiches-cours/ECL807/modelisation-de-la-biodiversite/), [{{< fa apple-whole >}} material](https://bios2.github.io/biodiversity_modelling_2021/)

##### ECL807 Advanced Field School in Computational Ecology 2023
Summer 2023, *Université de Sherbrooke and Université Laval*\
[{{< fa building-columns >}} admission](https://sentinellenord.ulaval.ca/en/ecology2023), [{{< fa star >}} Sentinelle Nord](https://sentinellenord.ulaval.ca/en
)

![We played the TrophIE Game during the Advanced Field School in Computational Ecology. This game simulates predator-prey dynamics by dividing players into three species: a top predator, an intermediate predator, and a prey. Prey could hide from top predators in refugees, but not from intermediate predators (!!). The goal of the game was to survive and find a mate to reproduce. We played in Parc Eco (Quebec), a forest environment. We collected geographical and interaction data and analyzed them for a class project. Picture credit: Sentinelle Nord, Université Laval.](pictures/courses/group_dead.jpg){width=400px}

##### Scientific collaboration in ecology and evolution
Fall 2022, *Living Data Project (LDP)*\
[{{< fa graduation-cap >}} LDP certificates](https://www.ciee-icee.ca/ldp-certificates.html)

##### Synthesis statistics for ecology and evolution
Fall 2021, *Living Data Project (LDP)*\
[{{< fa road >}} syllabus](https://osf.io/a9k5b/), [{{< fa graduation-cap >}} LDP certificates](https://www.ciee-icee.ca/ldp-certificates.html)

##### Short Course on Forecasting for Decision-Making: An Epidemiological & Ecological Perspective
Summer 2023, *Ecological Forecasting Initiative (EFI)*\
Fields Institute, Toronto\
[{{< fa road >}} syllabus](http://www.fields.utoronto.ca/activities/23-24/forecasting), [{{< fa brands github >}} repo](https://github.com/kbbodner/cefi_shortcourse_students_2023), [{{< fa virus >}} ecoforecast](https://ecoforecast.org/)